SELECT * FROM PERSON; 
SELECT * FROM TRAINER; 
SELECT * FROM TRAINEE; 
SELECT * FROM TRAINING; 
SELECT * FROM ITEM; 
SELECT * FROM USES; 
SELECT * FROM PERSON_ANOTHER_PHONE; 
SELECT * FROM ACTUAL_TRAINING; 
